### PR TITLE
Add SiteMinder related headers

### PR DESCRIPTION
**Pull request by ThePirateWhoSmellsOfSunflowers**
Hi!

This pull request adds SiteMinder  related headers to the list. SiteMinder is a SSO product  by CA/Symantec/Broadcom. Messing with these headers can lead to an authentication bypass :wink:

Cheers,

:sunflower:

### CODE REVIEW

**Comment by No0ob1e** [comment]
How to add it to an already installed extension?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!

Imo you have to clone my branch, rebuild it, and add it manually to your Burp Suite. I think, it's not possible to add to an existing extension without breaking something.

Or you can wait until repo owner merge my PR and push it on the BApps

:sunflower:

**Comment by vishwaratna** [comment]
unable to push to and create pull request.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Yes because my PR was create before the recent changes on the project. @albinowax ?

**Comment by albinowax** [comment]
Thanks for the ping. 

Before I merge this, I think the 'HTTP_' at the start of each siteminder variable name is added by the server, so instead of 'HTTP_SM_AUTHDIRNAME' we should probably simply send 'SM_AUTHDIRNAME'.  Can you confirm?

**Comment by albinowax** [comment]
Wow, that's a really nice finding, thanks for sharing. I'll merge it in as-is, and maybe do some digging to figure out whether we need the non-HTTP_ version as well later.

**Comment by jcmoreno** [comment]
Great contribution. I've done this before with SM_USER. I miss testing SM.

**Pull request merged**
