### PR TITLE
Remove albinowaxUtils-all.jar Dependency

### PR DESCRIPTION
**Pull request by ahanel13**
# High-Level Objective:
This pull request is the first step of many to migrate the extension to use the Montoya API. It involves the removal of the dependency on `albinowaxUtils-all.jar` and minor updates to make the migration to the Montoya API easier.

## Changes Made:
1. **Updated Vulnerable Dependencies:**
Libraries were being used which were affected by CVEs and it was an easy fix. After testing, no issues were detected with the version upgrades.

2. **Added Montoya API Dependency:**
Added the Montoya API dependency into the project and optimized dependency management by adding `maveLocal` to the repositories Gradle section. This enhancement minimizes redundant dependency pulls, utilizing cached dependencies instead.

3. **Removed Dependency on** `albinowaxUtils-all.jar`:
Eliminated the reliance on `albinowaxUtils-all.jar` due to its dependence on the Legacy API and the difficulty of updating code in the jar. Instead of migrating the entire `albinowaxUtils` repository separately, all classes from the JAR were implemented within the param-miner project and redundant classes will be removed in a future PR. This streamlines code management and simplifies migration to the Montoya API by consolidating the code into a single project.

4. **Updated Java Build Target to 21:**
Aligned the Java build target with the current version available in Burp. This update to Java 21 unlocks various code simplification features available in newer Java versions which will be present in future PRs.

## Additional Notes:
- The outlined changes collectively support the overarching goal of migrating to the Montoya API, ensuring smoother integration and improved project sustainability.
- The removal of the `albinowaxUtils-all.jar` dependency marks a strategic decision to consolidate code and streamline the migration process, simplifying future maintenance efforts.
- There is more logging now because I replaced all calls to the `Utilitites::log` function with `Utilities::out`. This was done because the `log` function was empty.

I tried to avoid making too many changes when implementing the albinowaxUtils classes, except for the Utilitites.java. 

_**If there is anything I can do to make this PR easier to review please let me know!**_

### CODE REVIEW

**Comment by ahanel13** [comment]
I completely understand and agree. 

The first thing I did when I saw the albinowaxUtils.jar was look at that repository. I was going to create a mirror of the functionally to handle the Montoya API. However,  I ran into a pretty big issue. The current repo doesn't have most of the classes that the param-miner project actually depends on. 

| # | Utility Classes found in the repository |
|---|----------------------------------------|
| 1 | BasicCollab                            |
| 2 | CollabInstance                         |
| 3 | ConfigurableSettings                   |
| 4 | LazyRequestInfo                        |
| 5 | Req                                    |
| 6 | Resp                                   |
| 7 | SettingsBox                            |
| 8 | Utilities                              |

| # | Utility Classes found in the jar       |
|---|----------------------------------------|
| 1 | Attack                                 |
| 2 | BasicCollab                            |
| 3 | BulkScan                               |
| 4 | BulkScanItem                           |
| 5 | BulkScanLauncher                       |
| 6 | ConfigListener                         |
| 7 | ConfigMenu                             |
| 8 | ConfigurableSettings                   |
| 9 | CustomScanIssue                        |
|10 | Fuzzable                               |
|11 | HeaderMutator                          |
|12 | LazyRequestInfo                        |
|13 | OfferBulkScan                          |
|14 | ParamInsertionPoint                    |
|15 | ParamScan                              |
|16 | PartialParam                           |
|17 | PayloadInjector                        |
|18 | Probe                                  |
|19 | ProbeResults                           |
|20 | RawInsertionPoint                      |
|21 | Req                                    |
|22 | Resp                                   |
|23 | Scan                                   |
|24 | ScanItem                               |
|25 | ScanPool                               |
|26 | Setting                                |
|27 | SettingsBox                            |
|28 | SortByParentDomain                     |
|29 | TriggerBulkScan                        |
|30 | Utilities                              |
|31 | ZgrabLoader                            |

I realized I would have to implement the classes anyways if I wanted to migrate them to use the Montoya API. 

I'm interested in contrubuting, but I might wait until the next release of the utils.

Thank you for your time!

**Comment by albinowax** [comment]
Right yes, these classes are missing due to the refactor that split albinowaxUtils into albinowaxUtils and bulkScan. You can find bulkScan here but it's outdated so waiting for everything to get synced up is the best strategy: https://github.com/albinowax/bulkScan

**Comment by albinowax** [comment]
@ahanel13 All the repos are now fully up to date so it's as suitable for work as it'll ever be at the moment. Sorry it took a while!

**Comment by ahanel13** [comment]
@albinowax Thank you for the heads up! Would you be open to releasing the Utilities Jar on something like a Maven repo so that others can see the referenced code when using an IDE? that way we wouldn't have to build/download the jar separately.

Then the dependency would be easier to manage since there would be versions associated with them.

**Comment by albinowax** [comment]
@ahanel13 yes that's an excellent idea. I'll see if I can do that this month.

**Pull request closed without merging**
